#!/bin/bash

LOGFILE=runner.log
DEBUGLOGFILE=debug.log
RUNNER_NAME=Runner
BASE_IMAGE=ghcr.io/tramlinehq/sonoma-runner-sm:latest

function log_output {
	echo "$(date "+%Y/%m/%d %H:%M:%S") [${RUN_ID:-PREPARING}] $1" >> $LOGFILE
}

function log_debug {
	echo "$(date "+%Y/%m/%d %H:%M:%S") $1" >> $DEBUGLOGFILE
}

function stream_output {
	while read -r line; do
		log_output "$line"
	done
}

eval "$(/opt/homebrew/bin/brew shellenv)"