---
- name: Configure Remote Mac Host Machine
  hosts: [mac1]
  become: yes
  tasks:

    - name: Generate SSH Key on Host Machine
      openssh_keypair:
        path: "/path/to/ssh/key"
        size: 2048

    - name: Pull MacOS/Tart Packages
      command: "cd /path/to/tart && git pull"

    - name: Git Clone Buildkansen
      git:
        repo: https://github.com/your/buildkansen.git
        dest: "/path/to/buildkansen"

    - name: Systemd Service for Go App
      systemd:
        name: buildkansen
        enabled: yes
        state: started
        daemon_reload: yes
        no_block: yes
        description: "Buildkansen Go App"
        exec_start: "/path/to/buildkansen/app"

    - name: Reload Nginx for Configuration Changes
      systemd:
        name: nginx
        state: reloaded
