---
- name: Setup Mac Mini
  hosts: macmini
  vars:
    release_version: v0.2.3

  tasks:
    - community.general.homebrew:
        name: caddy
    - community.general.homebrew:
        name: cirruslabs/cli/tart

    - name: Read-write git checkout from github
      git:
        repo: git@github.com:tramlinehq/buildkansen.git
        dest: /Users/administrator/buildkansen
        accept_hostkey: yes
      become: no

    - name: Generate an ssh key pair for vms
      openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_rsa_bullet"
        type: rsa
        size: 4096
        force: no
        state: present

    - name: Copy .env.production to svc
      copy:
        src: ../svc/.env.production
        dest: /Users/administrator/buildkansen/svc/.env
        owner: administrator
        group: staff
        mode: "0644"

    - name: Copy .env.production to host
      copy:
        src: ../host/.env.production
        dest: /Users/administrator/buildkansen/host/.env
        owner: administrator
        group: staff
        mode: "0644"

    - name: Ensure /usr/local/bin directory exists
      file:
        path: /usr/local/bin
        state: directory
        mode: 0755
        owner: administrator
        group: everyone
      become: yes

    - name: Copy buildkansen binary to server
      get_url:
        url: "https://github.com/tramlinehq/buildkansen/releases/download/{{release_version}}/buildkansen-darwin-arm64"
        dest: "/usr/local/bin/buildkansen"
        mode: 0755
        owner: administrator
        group: everyone

    - name: Copy com.tramline.buildkansen.plist to /Library/LaunchDaemons
      command: cp /Users/administrator/buildkansen/deployment/com.tramline.buildkansen.plist /Library/LaunchDaemons/com.tramline.buildkansen.plist
      become: yes

    - name: Unload com.tramline.buildkansen.plist via launchctl
      command: "launchctl unload /Library/LaunchDaemons/com.tramline.buildkansen.plist"
      become: yes

    - name: Load com.tramline.buildkansen.plist via launchctl
      command: "launchctl load -w /Library/LaunchDaemons/com.tramline.buildkansen.plist"
      become: yes

    - name: Check if service successfully started
      command: "launchctl list com.tramline.buildkansen | awk -F '= |;' '/LastExitStatus/{print $2}'"
      become: yes
      register: launchctl_output

    - name: Fail if service did not start
      fail:
        msg: "Could not start the service"
      when: launchctl_output.rc != 0

    - name: Create or update Caddyfile.j2
      template:
        src: Caddyfile.j2
        dest: /opt/homebrew/etc/Caddyfile

    - name: Reload caddy
      command: "/opt/homebrew/bin/brew services reload caddy"
