---
- name: Setup Mac Mini
  hosts: macmini
  vars:
    release_version: 0.1

  tasks:
    - community.general.homebrew:
        name: caddy
    - community.general.homebrew:
        name: cirruslabs/cli/tart

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: git@github.com:tramlinehq/buildkansen.git
        dest: /Users/administrator/buildkansen
        accept_hostkey: yes
      become: no

    - name: Copy .env.production to svc
      ansible.builtin.copy:
        src: ../svc/.env.production
        dest: /Users/administrator/buildkansen/svc/.env
        owner: administrator
        group: everyone
        mode: "0644"

    - name: Copy .env.production to host
      ansible.builtin.copy:
        src: ../host/.env.production
        dest: /Users/administrator/buildkansen/host/.env
        owner: administrator
        group: everyone
        mode: "0644"

    - name: Ensure /usr/local/bin directory exists
      file:
        path: /usr/local/bin
        state: directory
        mode: 0755
        owner: administrator
        group: everyone
      become: yes

    - name: Copy buildkansen binary to server
      get_url:
        url: "https://github.com/tramlinehq/buildkansen/releases/download/{{release_version}}/buildkansen-darwin-arm64"
        dest: "/usr/local/bin/buildkansen"
        mode: 0755
        owner: administrator
        group: everyone

    - name: Copy com.tramline.buildkansen.plist to /Library/LaunchDaemons
      command: cp /Users/administrator/buildkansen/deployment/com.tramline.buildkansen.plist /Library/LaunchDaemons/com.tramline.buildkansen.plist
      become: yes

    - name: Load com.tramline.buildkansen.plist using launchctl
      command: "launchctl load -w /Library/LaunchDaemons/com.tramline.buildkansen.plist"
      become: yes

    - name: Run the command and check exit code
      command: "launchctl list com.tramline.buildkansen | awk -F '= |;' '/LastExitStatus/{print $2}'"
      become: yes
      register: launchctl_output

    - name: Fail if exit code is non-zero
      fail:
        msg: "Could not start the service"
      when: launchctl_output.rc != 0

    - name: Create or update Caddyfile.j2
      template:
        src: Caddyfile.j2
        dest: /opt/homebrew/etc/Caddyfile
      notify: Reload Caddy

  handlers:
    - name: Reload Caddy
      command: "brew services reload caddy"
