default:
    @just --list

web:
    go run ./cmd/main.go

css:
    npm run watch

platform := env('PLATFORM', 'darwin')
arch := env('ARCH', 'arm64')

build:
    env GOOS={{platform}} GOARCH={{arch}} go build -o ./out/buildkansen-{{platform}}-{{arch}} ./cmd/main.go
